theme: jekyll-theme-slate
site_name: Core Lecture Note

pages:
  - Home: "index.md"
  - Microeconomics: "Microeconomics.html"
  - Macroeconomics: "Macroeconomics.html"
  - Econometrics: "Econometrics.html"