site_name: Core Lecture Note

theme: 
  name: "material"
  feature:
    tabs: true
    
pages:
  - Home: "index.md"
  - Microeconomics: "Microeconomics.md"
  - Macroeconomics: "Macroeconomics.md"
  - Econometrics: "Econometrics.md"